---
sidebar: sidebar 
permalink: automate-report-upgrade-health-checker.html 
keywords: upgrade, health, checker 
summary: È possibile automatizzare la generazione di report Upgrade Health Checker per ridurre lo sforzo manuale durante la pianificazione degli aggiornamenti ONTAP in ambienti di grandi dimensioni e complessi. 
---
= Automatizza la generazione di piani di upgrade con Upgrade Health Checker
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile automatizzare la generazione di report Upgrade Health Checker per ridurre lo sforzo manuale durante la pianificazione degli aggiornamenti ONTAP in ambienti di grandi dimensioni e complessi.

.Informazioni su questa attività
Upgrade Health Checker supporta gli aggiornamenti per le versioni ONTAP on-premises 9.11.1 e successive. Se si utilizza Cloud Volumes ONTAP, consultare link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-updating-ontap-cloud.html#supported-upgrade-paths["Aggiorna Cloud Volumes ONTAP"] per informazioni sull'aggiornamento del sistema.

.Passaggi
. Per garantire la corretta creazione dei report di aggiornamento, completare tutti i passaggi di configurazione necessari e le attività una tantum descritte in link:generate-report-upgrade-health-checker.html["Genera un report di aggiornamento ONTAP"].
. Crea uno script per eseguire Upgrade Health Checker con i parametri appropriati per il tuo ambiente.
+
[source, cli]
----
./uhc \
  --cluster-ip=<cluster-ip> \
  --cluster-username=<cluster-username> \
  --cluster-password=<cluster-password> \
  --target-ontap-version=<target-ontap-version> \
  --accept-eula=true
----
+
Ecco un esempio di un cronjob che esegue lo strumento dal lunedì al venerdì alle 4AM. I file binario e config.yaml sono stati installati in /opt/uhc/tool/.

+
Script Bash:

+
[listing]
----
#!/bin/bash
cd /opt/uhc/tool
/opt/uhc/tool/uhc --accept-eula true --cluster-ip cluster-mgmt1.example.com --target-ontap-version current --cluster-username uhctool --cluster-password passw0rd
/opt/uhc/tool/uhc --accept-eula true --cluster-ip cluster-mgmt2.example.com --target-ontap-version 9.14.1 --cluster-username uhctool --cluster-password passw0rd
----
+
Processo cron:

+
[listing]
----
0 4 * * 1-5 /usr/local/bin/uhccron.sh
----
. Dopo che Upgrade Health Checker ha completato i controlli, accedi alla  `runs` cartella per visualizzare il piano di aggiornamento e il report del cluster.
+

NOTE: Ogni esecuzione del programma è un'esecuzione unica e avrà tutti i dati, i log e i risultati associati nella cartella associata  `runs`.

. Apri il file di report (denominato  `uhc_<cluster-name>_<YYYYMMDDHHMMSS>`) in un browser web, Microsoft Excel o un visualizzatore JSON per visualizzare il report. Se esegui Upgrade Health Checker su un host remoto, scarica prima il file di report su un computer in cui puoi visualizzare il report in un browser web, in Excel o in un visualizzatore JSON.
+
Il percorso del registro e il percorso del report sono i seguenti:

+
** Percorso del registro: `<output-path>/<unique-run-dir>/<cluster-name>/logs`
** Percorso del report HTML: `<output-path>/<unique-run-dir>/<cluster-name>/results/uhc_<cluster-name>_<YYYYMMDDHHMMSS>.html`
** Percorso del report Excel: `<output-path>/<unique-run-dir>/<cluster-name>/results/uhc_<cluster-name>_<YYYYMMDDHHMMSS>.xlsx`
** Percorso del report JSON: `<output-path>/<unique-run-dir>/<cluster-name>/results/uhc_<cluster-name>_<YYYYMMDDHHMMSS>.json`



