---
sidebar: sidebar 
permalink: set-up-upgrade-health-checker.html 
keywords: upgrade, health, checker, set up, download 
summary: 'È possibile scaricare Upgrade Health Checker per generare report completi in loco prima di eseguire l"aggiornamento a una versione più recente di ONTAP.' 
---
= Scarica e configura Upgrade Health Checker
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile scaricare Upgrade Health Checker per generare report completi in loco prima di eseguire l'aggiornamento a una versione più recente di ONTAP.

.Informazioni su questa attività
Upgrade Health Checker supporta gli aggiornamenti per le versioni ONTAP on-premises 9.11.1 e successive. Se si utilizza Cloud Volumes ONTAP, consultare link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-updating-ontap-cloud.html#supported-upgrade-paths["Aggiorna Cloud Volumes ONTAP"] per informazioni sull'aggiornamento del sistema.

.Prima di iniziare
Configura una macchina virtuale per Upgrade Health Checker con le seguenti specifiche:

|===
| Componente | Specifiche 


 a| 
*VM*
| Macchina virtuale m5.large o equivalente con 2 vCPU e 8 GiB di RAM 


 a| 
*Sistema operativo*
| Qualsiasi sistema operativo Linux con libreria glibc versione 2.28 o superiore (Ubuntu 22.04, RHEL8 o RHEL9) 


 a| 
*Spazio su disco*
| Almeno 4 GB liberi (8 GB consigliati) in `/tmp` con permessi di esecuzione 


 a| 
*Rete*
| Connettività HTTPS alla LIF di gestione del cluster ONTAP 


 a| 
*versione di ONTAP*
| Cluster con ONTAP 9.11.1 o versioni successive 


 a| 
*Requisiti di hosting*
| Posiziona la macchina virtuale in una posizione con connettività al cluster e accesso a Internet per consentire gli aggiornamenti automatici degli strumenti. La macchina deve avere accesso ai seguenti endpoint tramite HTTPS (443) per eseguire gli aggiornamenti automatici e per consentire a NetApp di ricevere informazioni AutoSupport sui piani di aggiornamento: https://support.netapp.com/[] https://api.uhc.netapp.com[] https://gql.aiq.netapp.com[] https://api.activeiq.netapp.com[] 


 a| 
*Pacchetti consigliati*
| Installare un server web per facilitare l'accesso 
|===

NOTE: Assicurati che la macchina virtuale possa connettersi agli endpoint di aggiornamento automatico e telemetria (https://support.netapp.com/[] e  https://api.activeiq.netapp.com[] tramite HTTPS (443) per consentire a NetApp di ricevere informazioni AutoSupport sui tuoi piani di aggiornamento. Se non hai accesso a Internet, devi scaricare manualmente la versione più recente di Upgrade Health Checker.

.Passaggi
. Scarica il file binario di Upgrade Health Checker accedendo alla link:https://console.netapp.com/automationHub["Hub di automazione NetApp Console"^] e trovando il riquadro Upgrade Health Checker.
. Configura la macchina virtuale Upgrade Health Checker e usa SSH per posizionare il binario nella posizione di tua scelta.
. Verificare la firma digitale di Upgrade Health Checker.
+
Upgrade Health Checker ha un certificato di firma del codice pubblico (`UHC-Linux-codesigning-certificate-public.pem`) e una catena di certificati intermedi e radice (`UHC-Linux-chain-certificates-public.pem`).

+
.. (Facoltativo) Verificare il certificato di firma del codice rispetto alla catena:
+
[listing]
----
openssl verify -CAfile UHC-Linux-chain-certificates-public.pem UHC-Linux-codesigning-certificate-public.pem
----
+
Un output di  `OK` conferma una catena di fiducia valida.

.. Estrai la chiave pubblica dal certificato di firma del codice:
+
[listing]
----
openssl x509 -in UHC-Linux-codesigning-certificate-public.pem -pubkey -noout -out UHC-Linux-public.pub
----
.. Verificare il file di firma (`uhc.sig` rispetto al binario Upgrade Health Checker utilizzando la chiave pubblica:
+
[listing]
----
openssl dgst -sha256 -verify UHC-Linux-public.pub -signature uhc.sig uhc
----
+
Un output di  `Verified OK` conferma che la firma è valida.



. Configura un account di servizio e un ruolo per l'accesso al cluster ONTAP. Per l'accesso al cluster tramite Upgrade Health Checker, crea il ruolo di servizio come REST-role.
+

NOTE: È possibile creare un playbook Ansible per automatizzare la distribuzione del ruolo e dell'utente su tutti i cluster ONTAP.

+
È necessario creare l'account di servizio per l'applicazione HTTP. Utilizzare i seguenti comandi CLI per configurare le autorizzazioni necessarie:

+
[source, cli]
----
security login rest-role create -role uhctool -api /api -access readonly -vserver

security login rest-role create -role uhctool -api /api/support/autosupport -access read_create_modify -vserver

security login rest-role create -role uhctool -api /api/support/autosupport/messages -access read_create_modify -vserver

vserver services web access create -name spi -role uhctool -vserver

security login create -user-or-group-name uhctool -role uhctool -application http -authentication-method password

security login create -user-or-group-name uhctool -role uhctool -application ssh -authentication-method password
----
. (Facoltativo) Configura la gestione delle credenziali per proteggere l'accesso all'applicazione.
+
Ad esempio, se disponi di CyberArk e Conjur, puoi configurare il tuo ambiente in modo da evitare di passare le credenziali tramite un file yaml o una riga di comando.

+
.. Crea le casseforti CyberArk richieste:
+
... Crea una cassaforte (Main-Conjur-Safe) che contiene le credenziali e i segreti dell'applicazione
... Crea una Safe (API-Credentials-Safe) che contiene il Conjur Host ID e l'API Key
... Crea una Safe (Conjur-SSL-Certificate) che contenga il certificato necessario


.. Crea i file di configurazione (Conjur.conf) e di identità (Conjur.identity) per questa applicazione:
+
... Conjur.conf
+
[listing]
----
account:
plugins:[]
appliance_url: https://FQDN
cert_file: /etc/conjur.pem
----
... Conjur.identity
+
[listing]
----
machine https://FQDN/authn
login host /prodvault/devops/<Main-Conjur-Safe>/host1
password XXXXXX
----




+
Ecco un esempio di come utilizzare CyberArk e Conjur in un playbook Ansible:

+
.. Installa Conjur Ansible Collection, che include il Conjur Ansible Lookup Plugin, su Ansible Host:
+
[listing]
----
ansible-galaxy collection install cyberark.conjur
----
.. Crea un'attività in un file yaml per recuperare il nome utente e la password da CyberArk:
+
[listing]
----
conjur_username: "{{ lookup('cyberark.conjur.conjur_variable', 'prodvault/devops/<Main-Conjur-Safe>/<Account name>/username', validate_certs=false) }}"
conjur_password: "{{ lookup('cyberark.conjur.conjur_variable', 'prodvault/devops/<Main-Conjur-Safe>/<Account name>/password', validate_certs=false) }}"
----




.Informazioni correlate
* link:upgrade-health-checker-input-parameters.html["Scopri i parametri di input per Upgrade Health Checker"]


.E ora?
È possibile utilizzare Upgrade Health Checker per aiutarti a pianificare un aggiornamento di ONTAP link:generate-report-upgrade-health-checker.html["generazione di un report di aggiornamento"].
