---
sidebar: sidebar 
permalink: setup-email-upgrade-health-checker.html 
keywords: upgrade, health, checker 
summary: È possibile configurare le email per ricevere i report di Upgrade Health Checker. 
---
= Ricevi i report di verifica dello stato di aggiornamento via e-mail
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Upgrade Health Checker può inviare i report direttamente alla tua casella di posta. Abilita questa funzione tramite il file config.yaml o un argomento della riga di comando. Quando è abilitato, Upgrade Health Checker invia i report generati (HTML, Excel o JSON) a uno o più destinatari tramite un server SMTP. Quando è disabilitato, non viene inviato alcun report. Se la generazione del report non riesce e l'invio tramite email è abilitato, Upgrade Health Checker invia i file di log ai destinatari configurati.



[[configure-using-the-config-yaml-file]]
== Configura tramite il file config.yaml

Puoi configurare le impostazioni email nel file config.yaml abilitando i report email, aggiungendo i dettagli del server SMTP e specificando gli indirizzi dei destinatari e i formati dei report.

. Abilita i report via email nel file config.yaml.
+
[listing]
----
# Email Report Configuration
EMAIL:
  ENABLED: true
----
. Aggiungi le impostazioni di configurazione SMTP, i dettagli del mittente e l'oggetto:
+
[listing]
----
# SMTP Server Configuration
EMAIL:
  ENABLED: true
  FROM: "uhc-notify@example.com"
  SUBJECT: "UHC Upgrade Health Report"
  REPLY_TO: <email>
  SMTP:
    HOST: "smtp.example.com"
    PORT: [<port-number>]
----
. Aggiungi gli indirizzi email dei destinatari e imposta i formati dei report che il sistema invia via email, ad esempio HTML, EXCEL, JSON o ALL. Puoi anche usare l'autenticazione e la crittografia:
+
[listing]
----
# Recipient Email Addresses, report formats
EMAIL:
  ENABLED: true
  TO: <recipient>
  FROM: "uhc-notify@example.com"
  SUBJECT: "UHC Upgrade Health Report"
  REPLY_TO: <email>
  RECIPIENTS: "user1@example.com, user2@example.com"
  REPORT_FORMATS: "HTML,EXCEL,JSON"   # valid values: HTML, EXCEL, JSON or ALL
  SMTP:
    HOST: "smtp.example.com"
    PORT: [PORT]
    USE_SMTP_AUTH: true
    USE_TLS: true
    USE_SSL: true
    USERNAME: "user@example.com"
    PASSWORD: "********"
----




[[configure-using-command-line-arguments]]
== Configura tramite argomenti della riga di comando

Puoi configurare le impostazioni di base dell'email usando gli argomenti della riga di comando per abilitare i report, specificare i destinatari e scegliere i formati dei report.

. Abilita i report via e-mail tramite argomenti della riga di comando:
+
[listing]
----
./uhc --email-enabled=true
----
. Fornire gli indirizzi e-mail dei destinatari:
+
[listing]
----
./uhc --email-recipients="user1@example.com, user2@example.com"
----
. Configura quali formati di report devono essere inviati via e-mail, ad esempio HTML, EXCEL, JSON:
+
[listing]
----
./uhc --email-report-formats=HTML,EXCEL,JSON
----


[NOTE]
====
Puoi configurare i seguenti tre attributi tramite argomenti della riga di comando o il file config.yaml. Puoi configurare tutti gli altri attributi solo nel file config.yaml:

* E-mail abilitata
* Destinatari dell'e-mail
* Formati di report via e-mail


Tieni presente che gli argomenti della riga di comando sovrascrivono i valori del file config.yaml.

Ad esempio:

[listing]
----
./uhc \
  --email-enabled=true
  --email-recipients="user1@example.com, user2@example.com" \
  --email-report-formats=HTML,EXCEL,JSON \
----
[listing]
----
EMAIL:
  FROM: "uhc-notify@example.com"
  SUBJECT: "UHC Upgrade Health Report"
  REPLY_TO: <email>
  SMTP:
    HOST: "smtp.example.com"
    PORT: [PORT]
----
====