---
sidebar: sidebar 
permalink: setup-email-upgrade-health-checker.html 
keywords: upgrade, health, checker 
summary: È possibile configurare le email per ricevere i report di Upgrade Health Checker. 
---
= Ricevi i report di verifica dello stato di aggiornamento via e-mail
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile integrare le email in Upgrade Health Checker per ricevere i report direttamente nella propria casella di posta. Questa funzione si abilita tramite il file config.yaml o come argomento della riga di comando. Quando è abilitata, Upgrade Health Checker invia i report generati (HTML, Excel o JSON) a uno o più destinatari configurati tramite un server SMTP. Quando la funzione è disabilitata, non viene inviato alcun report. Se la generazione del report non riesce e l'email è abilitata, i file di log vengono inviati ai destinatari configurati.



== Configura tramite il file config.yaml

. Abilita i report via email nel file config.yaml.
+
[listing]
----
# Email Report Configuration
EMAIL:
  ENABLED: true
----
. Fornire le impostazioni di configurazione SMTP, i dettagli del mittente e l'oggetto:
+
[listing]
----
# SMTP Server Configuration
EMAIL:
  ENABLED: true
  FROM: "uhc-notify@example.com"
  SUBJECT: "UHC Upgrade Health Report"
  REPLY_TO: <email>
  SMTP:
    HOST: "smtp.example.com"
    PORT: [<port-number>]
----
. Fornire gli indirizzi e-mail dei destinatari e configurare i formati di report da inviare tramite e-mail, ad esempio HTML, EXCEL, JSON, ALL:
+
[listing]
----
# Recipient Email Addresses, report formats
EMAIL:
  ENABLED: true
  TO: <recipient>
  FROM: "uhc-notify@example.com"
  SUBJECT: "UHC Upgrade Health Report"
  REPLY_TO: <email>
  RECIPIENTS: "user1@example.com, user2@example.com"
  REPORT_FORMATS: "HTML,EXCEL,JSON"   # valid values: HTML, EXCEL, JSON or ALL
  SMTP:
    HOST: "smtp.example.com"
    PORT: [PORT]
----




== Configura tramite argomenti della riga di comando

. Abilita i report via e-mail tramite argomenti della riga di comando:
+
[listing]
----
./uhc --email-enabled=true
----
. Fornire gli indirizzi e-mail dei destinatari:
+
[listing]
----
./uhc --email-recipients="user1@example.com, user2@example.com"
----
. Configura quali formati di report devono essere inviati via e-mail, ad esempio HTML, EXCEL, JSON:
+
[listing]
----
./uhc --email-report-formats=HTML,EXCEL,JSON
----


[NOTE]
====
I seguenti tre attributi possono essere configurati sia tramite argomenti della riga di comando che tramite il file config.yaml; gli attributi rimanenti sono configurabili solo tramite il file config.yaml:

* E-mail abilitata
* Destinatari dell'e-mail
* Formati di report via e-mail


Si noti che, laddove vengano forniti argomenti da riga di comando, questi sovrascrivono i valori del file config.yaml.

Ad esempio:

[listing]
----
./uhc \
  --email-enabled=true
  --email-recipients="user1@example.com, user2@example.com" \
  --email-report-formats=HTML,EXCEL,JSON \
----
[listing]
----
EMAIL:
  FROM: "uhc-notify@example.com"
  SUBJECT: "UHC Upgrade Health Report"
  REPLY_TO: <email>
  SMTP:
    HOST: "smtp.example.com"
    PORT: [PORT]
----
====