---
sidebar: sidebar 
permalink: whats-new.html 
keywords: upgrade, health, checker, whats new, release, notes 
summary: Scopri le novità di questo sito di documentazione. 
---
= Novità in Upgrade Health Checker
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Scopri le novità di Upgrade Health Checker (UHC). Puoi trovare ulteriori informazioni sui miglioramenti accedendo al riquadro Upgrade Health Checker nel link:https://console.netapp.com/automationHub["Hub di automazione NetApp Console"^] e visualizzando i file di download più recenti di Upgrade Health Checker.



[[17-july-2026]]
== 17 luglio 2026

Questo aggiornamento introduce diversi miglioramenti, tra cui una dashboard per la visualizzazione dei rischi della flotta, il supporto per l'autenticazione e la crittografia delle e-mail, la creazione di report sul numero di unità, il supporto per la versione di ONTAP consigliata e i controlli IMT per NAS e SAN.

* Dashboard UHC: ora è disponibile la vista *Fleet Risk*
* Integrazione con la posta elettronica: supporto per un server di posta elettronica con autenticazione e crittografia
* Aggiunto *Conteggio unità* nel riepilogo del cluster nel report
* Versione di ONTAP consigliata ora supportata
* Aggiunto il supporto per i controlli IMT di NAS e SAN




[[11-june-2026]]
== 11 giugno 2026

Questo aggiornamento aggiunge l'invio di report tramite e-mail, un parametro nella dashboard per una rapida panoramica dello stato di salute e nuove sezioni di documentazione per aiutarti a gestire e risolvere i problemi di Upgrade Health Checker.

* UHC supporta l'invio diretto dei report alla tua casella di posta.
+
link:setup-email-upgrade-health-checker.html["Ricevi i report di verifica dello stato di aggiornamento via e-mail"].

* Introduce il  `--dashboard` parametro che rigenera la dashboard dalle esecuzioni esistenti  `<runs>/dashboard/index.html` senza contattare un cluster. Fornisce una high-level panoramica dello stato di salute di tutti i cluster a cui si è acceduto di recente.
+
link:dashboard-upgrade-health-checker.html["Aggiorna la dashboard di Health Checker"], link:upgrade-health-checker-input-parameters.html#dashboard["Parametro del dashboard"].

* Introduce una nuova sezione Manutenzione, Risoluzione dei problemi e Domande frequenti.
+
** Mantieni Upgrade Health Checker controllando la presenza di aggiornamenti, monitorando i log per problemi ricorrenti e verificando di configurare correttamente lo strumento.
+
link:maintain-upgrade-health-checker.html["Mantieni lo strumento di verifica dello stato di aggiornamento"].

** Risolvere i problemi comuni di Upgrade Health Checker e correggere gli errori che possono bloccare la pianificazione dell'aggiornamento di ONTAP.
+
link:troubleshoot-upgrade-health-checker.html["Risoluzione dei problemi Upgrade Health Checker"].

** Domande frequenti (FAQ) per Upgrade Health Checker.
+
link:faq-upgrade-health-checker.html["FAQ per Upgrade Health Checker"].







[[15-april-2026]]
== 15 aprile 2026

Questo aggiornamento aggiunge un nuovo formato di report XLSX e richiede l'accesso a un nuovo endpoint affinché gli aggiornamenti automatici funzionino.

* Devi concedere a UHC l'accesso a un nuovo endpoint (+https://api.activeiq.netapp.com+) perché le funzionalità di aggiornamento automatico funzionino.
+
link:set-up-upgrade-health-checker.html["Scarica e configura Upgrade Health Checker"].

* UHC ora offre un nuovo formato di report (.XLSX - modificabile dall'uomo) che va ad aggiungersi ai formati HTML (leggibile dall'uomo) e JSON (leggibile dalla macchina).
+
link:generate-report-upgrade-health-checker.html["Genera un report di aggiornamento ONTAP"].

+
link:automate-report-upgrade-health-checker.html["Automatizza la generazione di piani di upgrade con Upgrade Health Checker"].





[[13-february-2026]]
== 13 febbraio 2026

Upgrade Health Checker è ora disponibile. Questo strumento genera report dettagliati in loco per aiutarti a completare con successo l'aggiornamento di ONTAP. Puoi usare Upgrade Health Checker con i framework di automazione e orchestrazione esistenti per risparmiare tempo durante l'aggiornamento di cluster singoli o multipli. Upgrade Health Checker supporta gli aggiornamenti a ONTAP 9.11.1 e versioni successive.

link:learn-about-upgrade-health-checker.html["Scopri di più su Upgrade Health Checker"].
